### ISSUE TITLE
GH Action Error: Job 'ci' failed

### ISSUE THREAD

**Issue by bcral** [stratum-mining/stratum#392] opened 2022-12-27 19:56 UTC
This test seems to pass or fail randomly, both when run locally with the `.githooks/pre-push` test and on GH after a push.

The exact test that fails seems to change each time, but the common theme seems to be this error: `... panicked at 'attempt to add with overflow', protocols/v2/roles-logic-sv2/src/job_creator.rs:93:27` which is: `let template_id = template.template_id + 1;`

**Comment by xraid** [comment] 2022-12-28 00:04
did You try a `=+` also since the u64 might not have been initialize with value prior maybe try give a new default init = `1` at construction ?

**Comment by bcral** [comment] 2022-12-28 00:07
I didn't try anything yet, I just found the issue while I'm working on something similar, and wanted to open the issue for visibility.  It seems that many recent PRs have had failures on the CI action.

**Comment by xraid** [comment] 2022-12-28 01:13
```
let template_id = template.template_id.checked_add(1);
if template_id.is_none()
  template_id = 1
```

**Comment by Fi3** [comment] 2022-12-28 11:30
I'm gonna to solve this on https://github.com/stratum-mining/stratum/pull/391 cause is blocking the merge.

The issue can be solved patching the implementation (that is right) or the test (where the issue is)

Before patching it we should consider that 
1. in release mode rust wrap around the minimum if we overflow so the issue is not there
2. we want to rethink ids in general https://github.com/stratum-mining/stratum/issues/379

IMO best thing to do is just to explicitly use wrapping_add in the implementation so that binary in debug mode do the same thing as binary in release mode.

If we want to patch the test instead we have 2 options (let's say that x is a random u32)
1. `x.checked_sub(1).unwrap_or(0)`
2. `x % u32::MAX `

(2) use a division but it seem faster: https://godbolt.org/z/a8zTx6W49

The test should be fixed and marked with `#[quickcheck_macros::quickcheck]` to be a real prop test (right now it get executed only one time). So it could make sense to use the faster impl but we are not going to patch the test so who care.

**Closed by Fi3** 2022-12-28 11:30 UTC

**Comment by xraid** [comment] 2022-12-28 12:10
i se the template_id is a U64 so use a UID that could be timestamp.as_nanos()

now the dance around now is unnecessary complex ...

considering a **reference implementation** is to clearly convey and implement concepts in the specification and **not** be a playground for wannebesmartcode that is hard to read, understand, bugfix and maintain ...

**Comment by Fi3** [comment] 2022-12-28 12:23
What do you mean by that?

>> now the dance around now is unnecessary complex ...

**Comment by Fi3** [comment] 2022-12-28 12:24
agree that for template_id timestamp seem to be the right choice btw we I want to make sure that this wont lead to different template with equal ids but dosen't seem so

**Comment by Fi3** [comment] 2022-12-28 12:30
said that we can not use a timestamp in a prop test
