### ISSUE TITLE
TP enter invalid state when receive invalid messae

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#786] opened 2024-03-07 12:02 UTC
When we send an Sv2 message to the TP where the message header contains a payload len bigger than the actual payload len, the TP enter in an invalid state and must be killed cause is irresponsive. @Sjors 

- [ ] add a test
- [ ] fix the issue

**Comment by jakubtrnka** [comment] 2024-03-08 14:48
How to reproduce:

Perform normal initial noise handshake.
Then, instead of encrypted stratum-message, send these raw bytes to the TP: `"some arbitrary line of text"`

These two message appear in the infinite short loop:
```
2024-03-08T14:46:29Z [sv2:trace] Transport problem, disconnecting client id=1
2024-03-08T14:46:29Z [sv2:trace] Message decryption failed
```

**Comment by jakubtrnka** [comment] 2024-03-08 14:52
The same experiment with raw bytes `"aaaabbbbccccddddeeeeff"` correctly disconnects the client.

**Comment by Sjors** [comment] 2024-03-08 18:11
From your log it looks like the TP knows that it should disconnect, but then delays actually dropping the connection.

I believe that should be fixed now in https://github.com/bitcoin/bitcoin/pull/29432/commits/2114ca363a5ba34f0c7ec63a2eb11d6680002f9d) on the `sv2` branch (pushed to https://github.com/bitcoin/bitcoin/pull/29432, but I haven't tested.

**Comment by pavlenex** [comment] 2024-03-13 06:50
@Sjors Should we close this one?

**Comment by Sjors** [comment] 2024-03-18 10:33
It's better to wait if @Fi3 or @jakubtrnka can no longer reproduce the issue.

**Comment by jakubtrnka** [comment] 2024-03-18 14:50
I can no longer reproduce the issue. So it appears to be fixed.

BTW I noticed I no longer see the log message `Template Provider listening on port: ...` Even though it does listen. 

branch sv2@2114ca363a

**Comment by Sjors** [comment] 2024-03-18 16:21
I made a note to figure out how the "Template Provider listening on port:" message disappeared; I probably lost it in a rebase.

**Closed by Sjors** 2024-03-18 16:21 UTC
Labels: template provider
